### ISSUE TITLE
Possibility to get the data from other market?

### ISSUE THREAD

**Issue by taolivede** [shner-elmo/TradingView-Screener#1]
I really appreciate the great work from you. Thanks a lot.

Just one question, is it possible to get other market data (e.g., German market) through this API?

**Comment by shner-elmo** [comment]
Hello, glad you're enjoying it.

It should be possible,  [here](https://github.com/shner-elmo/TradingView-Screener/blob/5aaed207a42785fe86c6b4babe366b46122ce2af/tradingview_screener/query.py#L100) we specify the market to query the data from, try replacing that value with something like "germany", and let me know how it goes,

If that works I'll try finding the full list of markets and add it to the API.

**Comment by taolivede** [comment]
Hi, It works! I changed the country string in the URL as well.

Thanks!

**Comment by shner-elmo** [comment]
Great news, I will add this feature to the `master` branch in the future, cheers
