### ISSUE TITLE
How to find a certain field? 

### ISSUE THREAD

**Issue by jet-c-21** [shner-elmo/TradingView-Screener#12]
I want to select the symbol is in strong buy rating

**Comment by shner-elmo** [comment]
### Finding the "Technical Rating" Column:


To access the "Technical Rating" data in your DataFrame, you'll need to do some additional steps beyond retrieving the raw data. Here's how:

1. **Locate the Column**: Use `ctrl` + `f` to search for the desired column in the file `tradingview_screener/constants.py`. In this case, the column is named `Recommend.All`.

2. **Raw Data vs. Formatted Data**: This package retrieves raw data directly from TradingView's API. The website then uses JavaScript to format the values for user readability.

3. **Formatting the Data**: You'll need to create a custom function to convert the raw rating values into human-readable strings like "Buy" or "Sell".

---

The raw data:
```py
from tradingview_screener import Query

count, df = Query().select('Recommend.All').get_scanner_data()
print(df)
```
```
         ticker  Recommend.All
0      AMEX:SPY       0.466667
1   NASDAQ:TSLA       0.512121
2    NASDAQ:QQQ       0.466667
3   NASDAQ:NVDA       0.378788
4    NASDAQ:AMD       0.557576
..          ...            ...
45     NYSE:CRM       0.490909
46     NYSE:UNH       0.400000
47  NASDAQ:CRSP      -0.024242
48  NASDAQ:VCIT       0.354545
49     NYSE:BAC       0.557576

[50 rows x 2 columns]
```

And the data nicely formatted:
```py
# define a function to format rating values
def format_technical_rating(rating: float) -> str:
    if rating >= 0.5:
        return 'Strong Buy'
    elif rating >= 0.1:
        return 'Buy'
    elif rating >= -0.1:
        return 'Neutral'
    elif rating >= -0.5:
        return 'Sell'
    else:
        return 'Strong Sell'

# apply the formatting function to the column
df['rating'] = df['Recommend.All'].apply(format_technical_rating)

print(df)
```
```
         ticker  Recommend.All      rating
0      AMEX:SPY       0.466667         Buy
1   NASDAQ:TSLA       0.512121  Strong Buy
2    NASDAQ:QQQ       0.466667         Buy
3   NASDAQ:NVDA       0.378788         Buy
4    NASDAQ:AMD       0.557576  Strong Buy
..          ...            ...         ...
45     NYSE:CRM       0.490909         Buy
46     NYSE:UNH       0.400000         Buy
47  NASDAQ:CRSP      -0.024242     Neutral
48  NASDAQ:VCIT       0.354545         Buy
49     NYSE:BAC       0.557576  Strong Buy

[50 rows x 3 columns]
```

And just like that we got the same data as in the website, now you can follow the same process for the `Analyst Rating` field.

**Comment by shner-elmo** [comment]
As a side note, I don't intend to automatically format these values. This package is supposed to give the user the data in its raw format, which can be more useful in some cases.

However, I'm not against adding formatters for the most commonly used fields so users don't need to rewrite them from scratch each time.

**Comment by jet-c-21** [comment]
But I don't want the rating of "Technical Rating", I want to find the rating of "Analyst Rating", like the rating in the [stock forecast page](https://www.tradingview.com/symbols/NASDAQ-AAPL/forecast/)

**Comment by shner-elmo** [comment]
@jet-c-21 Yes I understand, follow the same process and you will find it. Its really easy.

**Comment by shner-elmo** [comment]
@jet-c-21 Sorry I misunderstood your initial question.
I did some digging and I found the fields you are looking for:
```py
cols = [
    'recommendation_over',
    'recommendation_total',
    'recommendation_sell',
    'recommendation_under',
    'recommendation_hold',
    'recommendation_mark',
    'recommendation_buy',
]

_, df = Query().select( *cols).set_tickers('NASDAQ:AAPL').get_scanner_data()
df.to_dict('records')
```
```py
[{'ticker': 'NASDAQ:AAPL',
  'recommendation_over': 5,
  'recommendation_total': 44,
  'recommendation_sell': 2,
  'recommendation_under': 1,
  'recommendation_hold': 14,
  'recommendation_mark': 1.5,
  'recommendation_buy': 22}]
```
![image](https://github.com/shner-elmo/TradingView-Screener/assets/102916448/138f67c2-634d-4d4d-9f4d-2558cbedd3b8)

And you can use the formatter from above for the `recommendation_mark` column. cheers
