### ISSUE TITLE
Query to extract all the financials of a ticker

### ISSUE THREAD

**Issue by Rajmehta123** [shner-elmo/TradingView-Screener#15]
Any query to extract all the financials for a set ticker?

Financials as provided on this link. https://www.tradingview.com/symbols/NASDAQ-AAPL/financials-overview/

![image](https://github.com/shner-elmo/TradingView-Screener/assets/22636443/36d4e673-7ebc-46ab-9bfd-adc17d78748d)

**Comment by shner-elmo** [comment]
Hello, its common courtesy to greet someone before asking for help.
