### ISSUE TITLE
Selected column is not appearing in the DataFrame

### ISSUE THREAD

**Issue by SAMSAMPOP** [shner-elmo/TradingView-Screener#16]
Hello Shneor,

Thank you very much for your reply.  Much appreciated.  

i am running a query which allows me to extract one of the fields I am interested in, 'Revenue (Quarterly QoQ Growth'.  I believe it is held in a JSON but could be wrong on this.  I am trying to understand how I can place the output from this query into a dataframe?  From there I can then manipulate the data, plot it and so on.

![image](https://github.com/shner-elmo/TradingView-Screener/assets/102916448/0a495256-f10c-40c4-8762-e0d3ee9b4df0)

Thank you very much,

Stephen

**Comment by shner-elmo** [comment]
Hey, the column you've selected: `Revenue (Quarterly QoQ Growth)`, is stored internally (by TradingView) as `total_revenue_qoq_growth_fq`. 
The former is just its display name, but its the same column.

As you can see the value for the ticker `MARA` is the same (although its rounded):
![image](https://github.com/shner-elmo/TradingView-Screener/assets/102916448/72e76a4c-e710-4250-a57a-79c7483a4800)
