### ISSUE TITLE
Comparing current close price with previous days

### ISSUE THREAD

**Issue by jvence** [shner-elmo/TradingView-Screener#17]
It would be helpful to allow the query to compare current price to previous price. For example, if we want to create a scanner that can identify stocks that had 3 down days, and today's low is lower than yesterday's low and current price is higher than yesterday's low.

**Comment by jvence** [comment]
Hello, yes I've installed and ran and understand very well what this project is about. This is a feature request and it's basically a way to screen stocks based on custom indicators. In case you're not familiar with custom indicators, here's an example: https://www.tradingview.com/script/kwQynp0T-Red-Dog-Reversal-Pattern/
And thank you for all your hard work.

**Comment by shner-elmo** [comment]
Btw its not possible. You can compare close to high, or the close of one timeframe to another (5 minutes Vs 1 month).
Have a look at the columns in `constants.py` there are some that might interest you, for example: `24h_close_change` or `24h_close_prev`.
