### ISSUE TITLE
Retrieve the next earnings date for a ticker but did receive a float not a date

### ISSUE THREAD

**Issue by optional12** [shner-elmo/TradingView-Screener#18]
My idea was to retrieve the next earnings date for a ticker so I checked your code and I think I found the corresponding column to use.
So I tried the customer screener with this query:

Python code used:
tmp = (Query()
 .select('name', 'earnings_release_date','Recent Earnings Date','earnings_release_next_date')
 .get_scanner_data())
df = tmp[1]
df[df.name == 'PFE']['earnings_release_next_date']

but getting floats instead of dates:

      ticker name  earnings_release_date  earnings_release_date earnings_release_next_date
48  NYSE:PFE  PFE           1.706615e+09 1.706615e+09                1.714478e+09

Can you please help/fix?

**Comment by shner-elmo** [comment]
Sure, so that number is a Unix/Epoch time. You can convert it to a datetime using the `datetime.datetime.utcfromtimestamp()`.

```py
_, df = Query().select('price', 'earnings_release_date').get_scanner_data()
df['earnings_release_date'] = df['earnings_release_date'].map(dt.datetime.utcfromtimestamp, na_action='ignore')
>>> df
```
```
          ticker        close earnings_release_date
0    NASDAQ:NVDA     672.8286   2023-11-21 21:21:00
1    NASDAQ:TSLA     183.1301   2024-01-24 21:19:00
2       AMEX:SPY     492.2399                   NaT
3     NASDAQ:QQQ     425.5300                   NaT
4    NASDAQ:SMCI     648.0000   2024-01-29 21:06:00
5     NASDAQ:AMD     166.6300   2024-01-30 21:15:00
6    NASDAQ:META     457.3000   2024-02-01 21:05:00
7      NYSE:PLTR      21.5800   2024-02-05 21:05:00
8     NYSE:BRK.A  591250.0212   2023-11-04 21:11:00
9    NASDAQ:AAPL     188.5027   2024-02-01 21:30:00
...
```

**Comment by optional12** [comment]
Your query uses a wrong field 'price', should be 'close'. But thanks for the clarification.

I know observed that not always data gets returned. 
Today for eaxmple for CRUS
df[df.name == 'CRUS'][['name', 'close', 'earnings_release_date', 'earnings_release_next_date']]
Empty DataFrame
Columns: [name, close, earnings_release_date, earnings_release_next_date]
Index: []

but on TradingView Earnings View/Screener page they are listed for today after Market
![image](https://github.com/shner-elmo/TradingView-Screener/assets/159178414/ce13b571-19b5-48c6-965d-92ce5cc1517c)

**Comment by shner-elmo** [comment]
Good catch. Glad you got it working now.
As for the ticket not appearing in the result, please open a separate issue for that.
