### ISSUE TITLE
cannot import name 'Screener' from 'tradingview_screener' 

### ISSUE THREAD

**Issue by GeavaPapi** [shner-elmo/TradingView-Screener#24]
I'm trying to run my python script, even on Replit i get everytime 
"Traceback (most recent call last):
  File "C:\xxx\tradinview\index.py", line 1, in <module>
    from tradingview_screener import Screener
ImportError: cannot import name 'Screener' from 'tradingview_screener'"

**Comment by shner-elmo** [comment]
It's
```py
from tradingview_screener import Scanner
```
