### ISSUE TITLE
Relative volume query change

### ISSUE THREAD

**Issue by Brilliantly-Stupid** [shner-elmo/TradingView-Screener#26]
Hello It seems like the   'Relative Volume': 'relative_volume_10d_calc'  no longer works.  It seems like the general 10 day relative volume has been changed to custom values.  

![image](https://github.com/shner-elmo/TradingView-Screener/assets/92904692/2b3e2e4b-4128-4121-8b00-3733310741b3)

**Comment by shner-elmo** [comment]
I'll have a look at this

**Comment by shner-elmo** [comment]
Did you check in [constants.py](https://github.com/shner-elmo/TradingView-Screener/blob/70a263bea60b7d57e0a4460feab96350a26082f0/src/tradingview_screener/constants.py#L3328-L3338)?

That column is indeed present there with all the timeframes in your picture. I tested it and it still works.

![image](https://github.com/shner-elmo/TradingView-Screener/assets/102916448/96a42914-03cf-41ed-a128-ad57de4ff30a)

To learn more about the timeframes [check this out](https://shner-elmo.github.io/TradingView-Screener/tradingview_screener/constants.html#COLUMNS).

**Comment by Brilliantly-Stupid** [comment]
I didnt see them in the constants before sorry. I must have missed it I only saw the intraday before. Thank you for the quick response, and the project its such a huge help keep up the great work!!

**Comment by shner-elmo** [comment]
Thank you! glad you are enjoying the project. If you have any recommendations I'm always open to feedback, cheers
