### ISSUE TITLE
Classic Fundamental Formulas

### ISSUE THREAD

**Issue by Esref2000** [shner-elmo/TradingView-Screener#30]
Thanks for this useful tool.

I wonder, if there is a way to get Beneish-M, Altman-Z, Springate Score etc. by your library...

In TradingView PineScript, these are built in:

ALTMAN_Z_SCORE = request.financial(syminfo.tickerid, "ALTMAN_Z_SCORE", "FY")

BENEISH_M_SCORE = request.financial(syminfo.tickerid, "BENEISH_M_SCORE", "FY")

FULMER_H_FACTOR = request.financial(syminfo.tickerid, "FULMER_H_FACTOR", "FY")

GRAHAM_NUMBERS = request.financial(syminfo.tickerid, "GRAHAM_NUMBERS", "FY")

KZ_INDEX = request.financial(syminfo.tickerid, "KZ_INDEX", "FY")

PIOTROSKI_F_SCORE = request.financial(syminfo.tickerid, "PIOTROSKI_F_SCORE", "FY")

SLOAN_RATIO = request.financial(syminfo.tickerid, "SLOAN_RATIO", "FY")

SPRINGATE_SCORE = request.financial(syminfo.tickerid, "SPRINGATE_SCORE", "FY")

TOBIN_Q_RATIO = request.financial(syminfo.tickerid, "TOBIN_Q_RATIO", "FY")

ZMIJEWSKI_SCORE = request.financial(syminfo.tickerid, "ZMIJEWSKI_SCORE", "FY")

**Comment by shner-elmo** [comment]
Hey, glad you enjoy it.
So you can only use indicators/columns that are present in the screener: 

![image](https://github.com/shner-elmo/TradingView-Screener/assets/102916448/6cf8df9a-8cd8-4f22-94ad-2aa9614a3d7f)

As far as I'm aware you cannot use scripts there, only in the chart.

**Comment by Esref2000** [comment]
Maybe, you can add a function for them.

For example, Beneish M score is calculated by the formula:

Beneish M Score = -4.840 + 0.920 x DSRI + 0.528 x GMI + 0.404 x AQ + 0.892 x SGI + 0.115 x DEPI - 0.172 x SGAI - 0.327 x LVGI + 4.697 x TATA

Definitions:

DSRI = (Net receivablest/ Salest) / Net receivablest-1 / Salest-1)

GMI = [(Salest-1 - COGSt-1) / Salest-1] / [(Salest- COGSt) / Salest]

AQI = [1 - (Current assetst+ PP&Et+ Securitiest) / Total assetst ] / [1 - ((Current assetst-1+ PP&Et-1 + Securitiest-1) / Total assetst-1)]

SGI = Salest/ Salest-1

DEPI = (Depreciationt-1/ (PP&Et-1+ Depreciationt-1)) / (Depreciationt/ (PP&Et+ Depreciationt))

SGAI = (SG&A Expenset/ Salest) / (SG&A Expenset-1/ Salest-1)

LVGI = [(Current liabilitiest+ Total long Term debtt) / Total assetst ] / [(Current liabilitiest-1+ Total long term debtt-1) / Total assetst-1]

TATA = (Income from continuing operationst - Cash flows from operationst) / Total assetst

**Comment by shner-elmo** [comment]
Its not possible.

But you can create and apply that function to the dataframe returned by `get_scanner_data()`.

**Comment by Esref2000** [comment]
> Its not possible.
> 
> But you can create and apply that function to the dataframe returned by `get_scanner_data()`.

I tried to use AI for that.

It generated this code, but its not working:

import tradingview_screener as tv
import pandas as pd

def get_tradingview_data(ticker):
    screener = tv.Screener()
    screener.add_stock(ticker)
    data = screener.get_data()

    balance_sheet = data['balance_sheet']
    financials = data['financials']
    cashflow = data['cashflow']
    
    total_assets = balance_sheet.loc['Total Assets', :]
    receivables = balance_sheet.loc['Net Receivables', :]
    sales = financials.loc['Total Revenue', :]
    cost_of_goods_sold = financials.loc['Cost Of Revenue', :]
    sga_expense = financials.loc['Selling General Administrative', :]
    current_assets = balance_sheet.loc['Total Current Assets', :]
    current_liabilities = balance_sheet.loc['Total Current Liabilities', :]
    depreciation = cashflow.loc['Depreciation', :]
    net_income = financials.loc['Net Income', :]
    ppe = balance_sheet.loc['Property Plant Equipment', :]
    cash = balance_sheet.loc['Cash', :]
    total_liabilities = balance_sheet.loc['Total Liab', :]

    return {
        'total_assets': total_assets,
        'receivables': receivables,
        'sales': sales,
        'cost_of_goods_sold': cost_of_goods_sold,
        'sga_expense': sga_expense,
        'current_assets': current_assets,
        'current_liabilities': current_liabilities,
        'depreciation': depreciation,
        'net_income': net_income,
        'ppe': ppe,
        'cash': cash,
        'total_liabilities': total_liabilities,
    }

def beneish_m_score(ticker):
    data = get_tradingview_data(ticker)
    
    period_1 = data['sales'].index[0]
    period_2 = data['sales'].index[1]

    # DSRI: Days Sales in Receivables Index
    dsri = (data['receivables'][period_1] / data['sales'][period_1]) / (data['receivables'][period_2] / data['sales'][period_2])
    
    # GMI: Gross Margin Index
    gmi = ((data['sales'][period_2] - data['cost_of_goods_sold'][period_2]) / data['sales'][period_2]) / ((data['sales'][period_1] - data['cost_of_goods_sold'][period_1]) / data['sales'][period_1])
    
    # AQI: Asset Quality Index
    aqi = (1 - (data['current_assets'][period_1] + data['ppe'][period_1] + data['cash'][period_1]) / data['total_assets'][period_1]) / (1 - (data['current_assets'][period_2] + data['ppe'][period_2] + data['cash'][period_2]) / data['total_assets'][period_2])
    
    # SGI: Sales Growth Index
    sgi = data['sales'][period_1] / data['sales'][period_2]
    
    # DEPI: Depreciation Index
    depi = (data['depreciation'][period_2] / (data['ppe'][period_2] + data['depreciation'][period_2])) / (data['depreciation'][period_1] / (data['ppe'][period_1] + data['depreciation'][period_1]))
    
    # SGAI: SGA Expenses Index
    sgai = (data['sga_expense'][period_1] / data['sales'][period_1]) / (data['sga_expense'][period_2] / data['sales'][period_2])
    
    # LVGI: Leverage Index
    lvgi = (data['total_liabilities'][period_1] / data['total_assets'][period_1]) / (data['total_liabilities'][period_2] / data['total_assets'][period_2])
    
    # TATA: Total Accruals to Total Assets
    tata = (data['net_income'][period_1] - data['cashflow']['Operating Cash Flow'][period_1]) / data['total_assets'][period_1]
    
    m_score = (
        -4.84
        + 0.920 * dsri
        + 0.528 * gmi
        + 0.404 * aqi
        + 0.892 * sgi
        + 0.115 * depi
        - 0.172 * sgai
        + 4.679 * tata
        - 0.327 * lvgi
    )
    
    return m_score

ticker = "AAPL"
m_score = beneish_m_score(ticker)
print(f"Beneish M-Score for {ticker}: {m_score}")
