### ISSUE TITLE
API Endpoint Specifications

### ISSUE THREAD

**Issue by FlorainK** [shner-elmo/TradingView-Screener#33]
Hi there,

first of all, thank you for this great library which has helped me out quite a lot.
I was searching for the specific endpoint from tradingview it is using, which I then found to be e.g. 'https://scanner.tradingview.com/america/scan'. Unfortunately I was not able to find the official documentation of this endpoint from tradingview's side. 
Could you please provide a link to these informations if they are available so I can check the general conditions of use / specifications.

Thanks in advance and best regards,
Florian

**Comment by shner-elmo** [comment]
Hey, glad you're enjoying it. There isn't any documentation as far as I know. 
(they only have an API for brokers for managing orders and stuff like that, but not a public API for customers like us).

What I've gathered so far is by tracking the network calls in the website.

You should have a pretty good idea on what kind of arguments that endpoint accepts by having a look at the source code of this package (also look as the `staging` branch where I implemented more features).
But if you have any questions, feel free to ask
