### ISSUE TITLE
Options Data

### ISSUE THREAD

**Issue by somethingbloodyfunky** [shner-elmo/TradingView-Screener#40]
I'm trying to get options data for the exchange `NSE`. However if I do, 

```
market = "options"
exchange = "NSE"
max_rows = 50000
#default_columns.remove('Market Capitalization')
(n_rows, df_) = Query().select(*default_columns).limit(max_rows).set_tickers('NSE:HDFCBANK').set_markets(market).get_scanner_data(cookies=cookies)
```

I get:

```
HTTPError: 400 Client Error: Bad Request
 Body: {"totalCount":0,"error":"required index \"underlying_symbol\" is missing from request","data":null}
 for url: https://scanner.tradingview.com/options/scan
```

Are `options` actually supported? If not, any tips on the correct HTTP request would be appreciated.

**Comment by shner-elmo** [comment]
So tradingview lists `options` as a market. So it definetly exists.

Now how do you access this data? I have yet to figure it out as there is no example on the website.

The error message says that you're missing the key 'underlying_symbol`, which I'm not sure how you are supposed to pass it, but you can try to add it manually; `q.query[key] = val`.

If you figure it out let us know.

**Comment by somethingbloodyfunky** [comment]
Many thanks Shneor for this excellent utility and your prompt response. :) I've been trying to hack away it since then as well but haven't been successful thus far. However, once I am, I will certainly revert.

**Comment by shner-elmo** [comment]
Thanks for your kind words! I'm glad to hear that you're finding the utility useful.

As an example, I tried the following changes but I still get the same error.

![image](https://github.com/user-attachments/assets/36f6d14e-1734-4a05-b2d2-1face46758af)

Also, I'm pretty sure that they either have or are working on options data, because they have `OPRA` in the list of exchanges [here](https://github.com/shner-elmo/TradingView-Screener/blob/docs/data/metainfo/options.json), and there are other fields like: `strike`, `expiration`, and `option-type`.

**Comment by shner-elmo** [comment]
I will keep this issue open, in the hopes that somebody will find a way to access the data and share it, cheers

**Comment by somethingbloodyfunky** [comment]
Thanks so much for your efforts! I tried something along those lines too, but have been unsuccessful thus far. 

Currently a search for `AAPL` does not list any options in TradingView any way.  In order to facilitate testing your code, may I suggest that for the Indian market, in particular the exchange NSE already has options data listed if you do a regular symbol search. E.g. `NIFTY240725C24600` is available and it can be loaded just like any other chart.

**Comment by shner-elmo** [comment]
Btw there is actually another way that you can select a certain market, its done by setting the `symbols.query.types` key:
```py
q = Query()
q.url = 'https://scanner.tradingview.com/global/scan'  # reset the URL to global
q.query['markets'] = []
q.query['symbols']['query']['types'] = ['forex']
q.get_scanner_data()
```
```
(6113,
                   ticker        name        close      volume market_cap_basic
 0        MOEX:CNYRUB_TOM  CNYRUB_TOM     11.97150  6119158000             None
 1        MOEX:KZTRUB_TOM  KZTRUB_TOM     18.49250  3240740000             None
 2        MOEX:AMDRUB_TOM  AMDRUB_TOM     22.99500   232340000             None
 3          FX_IDC:AUDITL      AUDITL   1188.98000     1067068             None
 4          FX_IDC:NZDITL      NZDITL   1068.93000     1067068             None
 ...
 45             FX:USDJPY      USDJPY    157.38100      353060             None
 46    PEPPERSTONE:USDJPY      USDJPY    157.52100      350233             None
 47       SKILLING:GBPJPY      GBPJPY    203.29800      264094             None
 48             FX:EURHUF      EURHUF    389.65600      137787             None
 49         FX_IDC:PENPTE      PENPTE     49.26230     1067111             None)
 ```
 
 The list of valid values are (for now):
 ```py
 ['fund',
  'stock',
  'dr',
  'spot',
  'swap',
  'futures',
  'structured',
  'index',
  'commodity',
  'option',
  'forex',
  'bond',
  'economic']
 ```
 And the `option` value is also present in the [metainfo file](https://github.com/shner-elmo/TradingView-Screener/blob/8e1b08b376e795e298895dcb188d581619f6d616/data/metainfo/options.json#L495-L501), but when we select that we receive an empty dataframe:
 
 ```py
q = Query()
q.url = 'https://scanner.tradingview.com/global/scan'
q.query['markets'] = []
q.query['symbols']['query']['types'] = ['option']
q.get_scanner_data()
```
```
(0,
 Empty DataFrame
 Columns: [ticker, name, close, volume, market_cap_basic]
 Index: [])
```

And its the only type in the list mentioned above that returns an empty DF, this leads me to believe that they have no options data yet, but they might be working on it.

**Comment by shner-elmo** [comment]
Also if you do:
```py
q = Query()
q.select('market')
q.limit(1_000_000)
q.url = 'https://scanner.tradingview.com/global/scan'
q.query['markets'] = []
_, df = q.get_scanner_data()

print(df['market'].value_counts().to_dict())
```
```
{'bond': 194590,
 'futures': 75443,
 'crypto': 42884,
 'germany': 20926,
 'america': 17758,
 'economics2': 14530,
 'canada': 7833,
 'uk': 7825,
 'india': 7031,
 'china': 6593,
 'forex': 6113,
 'japan': 4393,
 'korea': 3984,
 'italy': 3143,
 'mexico': 2771,
 'hongkong': 2735,
 'switzerland': 2532,
 'taiwan': 2495,
 'australia': 2255,
 'brazil': 2143,
 'thailand': 1811,
 'vietnam': 1332,
 'france': 1294,
 'sweden': 1218,
 'bonds': 1078,
 'malaysia': 1048,
 'israel': 1035,
 'austria': 944,
 'indonesia': 901,
 'coin': 804,
 'poland': 777,
 'netherlands': 653,
 'singapore': 612,
 'turkey': 596,
 'argentina': 554,
 'pakistan': 462,
 'cfd': 440,
 'bangladesh': 394,
 'rsa': 365,
 'ksa': 342,
 'norway': 331,
 'russia': 313,
 'luxembourg': 312,
 'philippines': 302,
 'srilanka': 288,
 'spain': 266,
 'egypt': 248,
 'romania': 232,
 'peru': 215,
 'finland': 192,
 'chile': 188,
 'denmark': 165,
 'newzealand': 164,
 'uae': 159,
 'greece': 151,
 'kuwait': 141,
 'nigeria': 130,
 'colombia': 125,
 'belgium': 119,
 'hungary': 80,
 'tunisia': 74,
 'morocco': 70,
 'czech': 57,
 'qatar': 54,
 'kenya': 54,
 'cyprus': 40,
 'portugal': 39,
 'venezuela': 33,
 'iceland': 31,
 'estonia': 31,
 'lithuania': 27,
 'serbia': 20,
 'bahrain': 19,
 'latvia': 11,
 'slovakia': 7}
```
You wont find any rows with the `options` market.

Rip, there really is no options data yet :(

**Comment by hachecito** [comment]
Hi @shner-elmo  @somethingbloodyfunky 
                                                                                                                                                                                            
  The error (`required index 'underlying_symbol' is missing`) happens because options use a different endpoint (`scan2`) with a different payload structure. `set_markets('options')` hits  
  `/options/scan` which doesn't work the same way.                                                                                                                                          
                                                                                                                                                                                            
  Two fixes:      
  1. Use `/options/scan2` instead of `/options/scan`
  2. Pass the underlying symbol via `index_filters`, not `set_tickers()`

  **Working example:**

  ```python
  from tradingview_screener import Query
  import pandas as pd

  COLUMNS = ['ask', 'bid', 'delta', 'expiration', 'gamma', 'iv',
             'option-type', 'strike', 'theta', 'vega', 'root']

  q = Query()
  q.url = 'https://scanner.tradingview.com/options/scan2'
  q.query = {
      'columns': COLUMNS,
      'ignore_unknown_fields': False,
      'index_filters': [{'name': 'underlying_symbol', 'values': ['NASDAQ:AAPL']}],
      'filter2': {
          'operator': 'and',
          'operands': [
              {'expression': {'left': 'type', 'operation': 'equal', 'right': 'option'}}
          ]
      },
      'range': [0, 500]
  }

  raw = q.get_scanner_data_raw(params={'label-product': 'options-builder'})
  symbols = raw.get('symbols', [])

  df = pd.DataFrame(
      [(item['s'], *item['f']) for item in symbols],
      columns=['ticker'] + COLUMNS
  )
  print(f"Contracts: {len(df)}")
  print(df.head())
  ```

**Note:** the options response format differs from the standard screener — it returns `symbols[].f` instead of `data[].d`, so `get_scanner_data()` won't work directly. Use
`get_scanner_data_raw()` and parse manually as shown above.

**Comment by shner-elmo** [comment]
@hachecito This is pretty cool, thanks for sharing!

I'll reopen this issue and hopefully I'll be able to implement it and publish a new version in the near future

**Comment by shner-elmo** [comment]
@hachecito wanted to ask you, how did you figure this out? is there anything in TradingView's website that polls this endpoint?
I want to look for more examples...

**Comment by hachecito** [comment]
@shner-elmo  When you open "Options" in TradingView you can see multiple calls to this url in the "Network" tab

<img width="1379" height="484" alt="Image" src="https://github.com/user-attachments/assets/995b5802-ff42-42e6-813e-1643ed1e2332" />

**Comment by shner-elmo** [comment]
Hey guys, I fixed it and added a new `options()` function (the underlying_symbol parameter is required by the API).

To try it, download the pre-release version:

```
pip install "tradingview-screener==3.2.0a1"                                                                                                                                                                     
```
and run
```py
from tradingview_screener import options

options('NASDAQ:AAPL').limit(10).get_scanner_data()
```
```
                 ticker     ask     bid  ...      vega    bid_iv    ask_iv
0  OPRA:AAPL261218P85.0    0.14    0.05  ...  0.014680  0.518856  0.578570
1  OPRA:AAPL260427C282.5    0.05    0.03  ...  0.011406  0.223944  0.241740
2  OPRA:AAPL260429P260.0    0.48    0.44  ...  0.056444  0.288474  0.295590
3  OPRA:AAPL260508C180.0   92.40   89.30  ...  0.003465       NaN  1.344026
4  OPRA:AAPL260427P242.5    0.03    0.01  ...  0.003072  0.467704  0.527473
5  OPRA:AAPL261218P325.0   58.15   54.95  ...  0.677275  0.192413  0.247696
6  OPRA:AAPL260508C355.0    0.43    0.00  ...  0.003957       NaN  0.538520
7  OPRA:AAPL260529C240.0   34.15   32.05  ...  0.146053  0.291427  0.417787
8  OPRA:AAPL261016C345.0    2.43    2.26  ...  0.347608  0.255966  0.260847
9  OPRA:AAPL261120P380.0  110.85  107.20  ...  0.240082       NaN  0.342871
[10 rows x 18 columns]
```

**Comment by shner-elmo** [comment]
let me know what you think, and in a week I will publish it in a stable version

**Comment by hachecito** [comment]
@shner-elmo Great! I'll give it a try! Let me know when a new version is available.

**Comment by shner-elmo** [comment]
I pubblished it today!

`pip install tradingview-screener==3.2.0`

@hachecito
