### ISSUE TITLE
How do I get historical data for a stock？

### ISSUE THREAD

**Issue by leoyb** [shner-elmo/TradingView-Screener#46]
How can I get one ticker historical data like daily closing prices, trading volume, and various indicators by screener

**Comment by hitemel** [comment]
Yes please help us, I need to reach the historical data. As I see, there is no way for it. All samples and information is about actual data.

**Comment by shner-elmo** [comment]
I believe there is another issue about this, but no.
It's not possible to get historical data with this library (or the screener API endpoint)
