### ISSUE TITLE
About DEMA Indicator

### ISSUE THREAD

**Issue by hitemel** [shner-elmo/TradingView-Screener#47]
Hello,

I think there is no column for DEMA indicator? And I need RSI(DEMA) results, if it is possible.

Thanks

**Comment by shner-elmo** [comment]
Hey, did you search in the page with all the fields?
And is this a column that you can select on the screener? (On the website)

**Comment by hitemel** [comment]
> Hey, did you search in the page with all the fields? And is this a column that you can select on the screener? (On the website)

Yes I checked all the columns. There is EMA variations but there is no for DEMA. For this reason I wanted historical data to calculate it myself.

**Comment by shner-elmo** [comment]
I see. You can call the `get_scanner_data()` function like once every minute and calculate it manually
