### ISSUE TITLE
Restricted refresh rate

### ISSUE THREAD

**Issue by Tim0tea** [shner-elmo/TradingView-Screener#50]
Hi, 

Data seems to only refresh every minute. Is there a way to improve this?

Thanks,

**Comment by shner-elmo** [comment]
Hey, did you read the README? 
Have a look at the real-time data section, you need to authenticate.

**Comment by Tim0tea** [comment]
Hi, thanks for response, turns out cookies had stopped working. I'm using manual cookies now and I can see increased refresh rate. 
Prices seems to refresh every 30seconds now, which is inline with trading view. 
Do you know anyway to increase refresh rate beyond 30seconds? This would be limited by trading view, but are you aware of any additional subscriptions to achieve faster rate? 
Thanks for support.

**Comment by shner-elmo** [comment]
Keep in mind that cookies expire after 3 months maximum.
As for the live data, if the cookies work, the only thing that might affect the refresh rate is if you purchased a live data subscription through trading view
