### ISSUE TITLE
Error "unknown field" when attempting to get live price using "query = Query().select('price')"

### ISSUE THREAD

**Issue by HondaCivicR** [shner-elmo/TradingView-Screener#52]
I am using this library to screen for stocks.

Example:

`query = Query().select('exchange', 'name', 'premarket_change', 'change_from_open', 'price')`
`    query.where(`
`       Column('premarket_change') > 10,`
`	Column('change_from_open') > 5,`
`	Column('exchange') != "OTC",`
`       )`

In the first line, if I remove the 'price' key, everything works fine. When I use it (to try to get the live price of a stock), I get this error:

`requests.exceptions.HTTPError: 400 Client Error: Bad Request`
` Body: {"totalCount":0,"error":"Unknown field \"price\"","data":null}`
` for url: https://scanner.tradingview.com/america/scan`

I suspect that to get the live price, a different key must be used, but I am not able to find which one. I have tried "current_price", "last", "last_price" and "price_last", none of them work

**Comment by HondaCivicR** [comment]
After further looking into this, Ive stumbled upon this page:

https://shner-elmo.github.io/TradingView-Screener/fields/stocks.html

To get the live price, you use the "close" key.

**Comment by shner-elmo** [comment]
Hey man! Glad you solved it

**Comment by wasiuddin1** [comment]
Use column close.
