### ISSUE TITLE
ADR% filter

### ISSUE THREAD

**Issue by jn11** [shner-elmo/TradingView-Screener#55]
Hi, when I use the screener with the TradingView desktop app using the "ADR% >= 50%" filter I got 554 symbols:

![Capture_screener](https://github.com/user-attachments/assets/ad3738ab-f4cf-4800-8806-930e7aa7f46d)

However when I run the same screener through this script I only get 23 symbols:

`
from tradingview_screener import Query, Column
q8 = Query().select('name', 'close', 'volume')
q8 .where(
     Column('ADR')  >= 50,
 )
q8.get_scanner_data()
`

< {'columns': ['name', 'close', 'volume'],
 'filter': [{'left': 'ADR', 'operation': 'egreater', 'right': 50}],
 'markets': ['america'],
 'options': {'lang': 'en'},
 'range': [0, 50],
 'sort': {'sortBy': 'Value.Traded', 'sortOrder': 'desc'},
 'symbols': {'query': {'types': []}, 'tickers': []}} >
>>>
>>> q8.get_scanner_data()
(**23**,           ticker   name        close  volume
0       NYSE:TPL    TPL    1730.0000  735674
1    NASDAQ:BKNG   BKNG    5177.1500  229480
2     NYSE:BRK.A  BRK.A  714280.0000    1527
3    NASDAQ:MELI   MELI    2005.0000  414128
4       NYSE:AZO    AZO    3099.3800  125961
5       NYSE:NVR    NVR    9007.2400   32317
6   NASDAQ:FCNCA  FCNCA    2353.0800   93165
7      NYSE:FICO   FICO    2355.3500   90174
8       OTC:GSOL   GSOL     181.3175   25116
9       AMEX:SEB    SEB    2663.0000    1312
10     OTC:CNSWF  CNSWF    3287.6000    1046
11     OTC:HESAF  HESAF    2111.5000     147
12     OTC:FCNCB  FCNCB    1964.0000      74
13      OTC:DVLN   DVLN    4600.0000      21
14      OTC:FINN   FINN   12200.0000       7
15     OTC:ADYYF  ADYYF    1314.0000      48
16     OTC:BVERS  BVERS    3350.0000      14
17      OTC:FMBL   FMBL    5650.0000       8
18     OTC:FNMFO  FNMFO   25300.0000       1
19     OTC:LDSVF  LDSVF   11350.0000       2
20      OTC:LICT   LICT   13800.0000       1
21      OTC:SBNC   SBNC    7225.0100       1
22     OTC:CBBBD  CBBBD       0.7521     262)

I don't know why there's this big difference. Is there any issue with the ADR% filter?

Thank you

**Comment by asemx** [comment]
You need to use "ADRP" , not  "ADR".

you can use chrome debug tools on tradingview scanner page to see the actual "dict"

**Comment by shner-elmo** [comment]
I suppose I can mark it as solved. (Thanks @asemx!)

**Comment by shner-elmo** [comment]
In the future, you can use this website to search for a specific field:
https://shner-elmo.github.io/TradingView-Screener/fields/stocks.html

![image](https://github.com/user-attachments/assets/b78365f2-c811-4e72-81d6-6249909e94d4)
